name: ~ci
on:
  workflow_call:
    inputs:
      scope:
        required: false
        type: string
      scope_package:
        required: false
        type: string
      scope_creator:
        required: false
        type: string
        default: pypi
      token:
        required: true
        type: string
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ inputs.scope_creator }}/dekspider
          token: ${{ inputs.token }}
          path: build
      - uses: actions/checkout@v3
        with:
          path: code
      - run: |-
          set -e
          export INPUTS__SCOPE_CREATOR=${{ inputs.scope_creator }}
          export INPUTS__TOKEN=${{ inputs.token }}
          export INPUTS__SCOPE_PACKAGE=${{ inputs.scope_package }}
          if [ "${{ inputs.scope }}" == "" ] ;then 
            export INPUTS__SCOPE=$(echo "$GITHUB_REPOSITORY" | cut -d "/" -f 1) 
          else 
            export INPUTS__SCOPE="${{ inputs.scope }}" 
          fi
          
          DOMAIN=$(echo "$GITHUB_SERVER_URL" | sed 's/^http\(\|s\):\/\///g')
          dekartifacts image login "$DOMAIN" "$GITHUB_ACTOR" "$INPUTS__TOKEN"    
          
          git -C ./build checkout $(git -C ./build describe --tags --all)

          if test -f "./build/.project/main.sh" ;then 
            bash ./build/.project/main.sh
          elif test -f "./build/.project/main.pysh" ;then 
            dekshell rf ./build/.project/main.pysh
          fi
