name: ~cd
on:
  workflow_call:
    inputs:
      scope:
        required: true
        type: string
      scope_package:
        required: false
        type: string
      token:
        required: true
        type: string
      environment:
        required: true
        type: string
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: pypi/djcreator
          token: ${{ inputs.token }}
          path: deploy
      - run: |-
          set -e
          export INPUTS__ENVIRONMENT=${{ inputs.environment }}
          export INPUTS__TOKEN=${{ inputs.token }}
          export INPUTS__SCOPE_PACKAGE=${{ inputs.scope_package }}
          if [ "${{ inputs.scope }}" == "" ] ;then 
            export INPUTS__SCOPE=$(echo "$GITHUB_REPOSITORY" | cut -d "/" -f 1) 
          else 
            export INPUTS__SCOPE="${{ inputs.scope }}" 
          fi
          git -C ./deploy checkout $(git -C ./build describe --tags --all)
          bash ./deploy/.cd/main.sh
