name: ~ci
on:
  workflow_call:
    inputs:
      scope:
        required: true
        type: string
      token:
        required: true
        type: string
      env:
        required: true
        type: string
      shortcut:
        required: true
        type: string
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: deploy/djcreator-vue
          token: ${{ inputs.token }}
          path: deploy
      - uses: actions/checkout@v3
        with:
          path: code
      - run: bash ./deploy/shell/ci.sh
        env:
          INPUTS__SCOPE: ${{ inputs.scope }}
          INPUTS__TOKEN: ${{ inputs.token }}
          INPUTS__ENV: ${{ inputs.env }}
          INPUTS__SECRETS_SHORTCUT: ${{ inputs.shortcut }}
