name: ~helm publish self
on:
  workflow_call:
    inputs:
      scope:
        required: false
        type: string
      scope_package:
        required: false
        type: string
      token:
        required: true
        type: string
      prepare:
        required: false
        type: string
      path:
        required: true
        type: string
jobs:
  publish-self:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |-
          set -e
          export INPUTS__TOKEN=${{ inputs.token }}
          export INPUTS__SCOPE_PACKAGE=${{ inputs.scope_package }}
          if [ "${{ inputs.scope }}" == "" ] ;then 
            export INPUTS__SCOPE=$(echo "$GITHUB_REPOSITORY" | cut -d "/" -f 1) 
          else 
            export INPUTS__SCOPE="${{ inputs.scope }}" 
          fi
          DOMAIN=$(echo "$GITHUB_SERVER_URL" | sed 's/^http\(\|s\):\/\///g')
          dekartifacts image login "$DOMAIN" "$GITHUB_ACTOR" "$INPUTS__TOKEN"    
          
          if test -f "${{ inputs.prepare }}" ;then 
            bash ${{ inputs.prepare }} 
          fi
          
          TARGET=$(cat ${{ inputs.path }}/dest.docker)
          docker build --no-cache -t $TARGET ${{ inputs.path }}
          dektools cmd retry docker push $TARGET
