name: ~helm publish self
on:
  workflow_call:
    inputs:
      scope:
        required: false
        type: string
      token:
        required: true
        type: string
      prepare:
        required: false
        type: string
      path:
        required: true
        type: string
jobs:
  publish-self:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |-
          set -e
          if [ "${{ inputs.scope }}" == "" ] ;then INPUTS__SCOPE=$(echo "$GITHUB_REPOSITORY" | cut -d "/" -f 1) ;else INPUTS__SCOPE="${{ inputs.scope }}" ;fi
          if test -f "${{ inputs.prepare }}" ;then echo execute ${{ inputs.prepare }} ;bash ${{ inputs.prepare }} "$INPUTS__SCOPE" "${{ inputs.token }}" ;fi
          DOMAIN=$(echo "$GITHUB_SERVER_URL" | sed 's/^http\(\|s\):\/\///g')
          dekartifacts image login "$DOMAIN" "$GITHUB_ACTOR" "${{ inputs.token }}"    
          TARGET=$(cat ${{ inputs.path }}/dest.docker)
          docker build --no-cache -t $TARGET ${{ inputs.path }}
          docker push $TARGET
