name: ~helm publish self
on:
  workflow_call:
    inputs:
      scope:
        required: false
        type: string
      token:
        required: true
        type: string
      prepare:
        required: false
        type: string
      path:
        required: true
        type: string
jobs:
  publish-self:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |-
          set -e
          export INPUTS__TOKEN=${{ inputs.token }}
          if [ "${{ inputs.scope }}" == "" ] ;then 
            export INPUTS__SCOPE=$(echo "$GITHUB_REPOSITORY" | cut -d "/" -f 1) 
          else 
            export INPUTS__SCOPE="${{ inputs.scope }}" 
          fi
          if test -f "${{ inputs.prepare }}" ;then 
            bash ${{ inputs.prepare }} 
          fi
          helm dependency update ${{ inputs.path }}
          helm package ${{ inputs.path }}
          for filename in ./*.tgz; do break; done;
          curl -f --user ${{ env.GITHUB_ACTOR }}:$INPUTS__TOKEN -X POST --upload-file ./$filename $GITHUB_SERVER_URL/api/packages/$INPUTS__SCOPE/helm/api/charts
