name: ~helm publish self
on:
  workflow_call:
    inputs:
      scope:
        required: true
        type: string
      token:
        required: true
        type: string
      prepare:
        required: true
        type: string
      path:
        required: true
        type: string
jobs:
  publish-self:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |-
          set -e
          if test -f ${{ inputs.prepare }} ;then echo execute ${{ inputs.prepare }} ;bash ${{ inputs.prepare }} "${{ inputs.scope }}" "${{ inputs.token }}" ;fi
          helm dependency update ${{ inputs.path }}
          helm package ${{ inputs.path }}
          for filename in ./*.tgz; do break; done;
          curl -f --user ${{ env.GITHUB_ACTOR }}:${{ inputs.token }} -X POST --upload-file ./$filename $GITHUB_SERVER_URL/api/packages/${{ inputs.scope }}/helm/api/charts
