name: ~npm publish
on:
  workflow_call:
    inputs:
      scope:
        required: true
        type: string
    secrets:
      token:
        required: true
jobs:
  publish-self-abc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |-
        deknp install
        sudo npm config set @${{ inputs.scope }}:registry=$GITHUB_SERVER_URL/api/packages/${{ inputs.scope }}/npm/
        sudo npm config set -- "//$(echo $GITHUB_SERVER_URL | sed 's/^http\(\|s\):\/\///g')/api/packages/${{ inputs.scope }}/npm/:_authToken" "${{ secrets.token }}"
        sudo npm publish
