name: ~release
on:
  workflow_call:

jobs:
  release-abc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/gitea-release-action@v1
