name: ~release
on:
  workflow_call:
    inputs:
      uploads:
        required: false
        type: string
      commands:
        required: false
        type: string
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: |
          ${{ inputs.commands }}
      - uses: actions/gitea-release-action@v1
        with:
          files: |-
            ${{ inputs.uploads }}
