name: ~npm publish
on:
  workflow_call:
    inputs:
      registry:
        required: false
        type: string
      scope:
        required: false
        type: string
    secrets:
      token:
        required: false
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 8
        run_install: false
    - name: Set node version to 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: https://registry.npmjs.org/
        cache: "pnpm"
    - run: |-
        set -e
        python3 -m pip install deknp
        deknp sure
    - name: Publish package
      run: pnpm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.token || secrets.NPM_TOKEN }}
        NPM_TOKEN: ${{ secrets.token || secrets.NPM_TOKEN }}
