name: ~npm publish
on:
  workflow_call:
    inputs:
      registry:
        required: false
        type: string
      scope:
        required: false
        type: string
    secrets:
      token:
        required: false
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - run: |-
        set -e
        npm install -g pnpm
        python3 -m pip install deknp
        deknp sure
    - uses: JS-DevTools/npm-publish@v3
      with:
        token: ${{ secrets.token || secrets.NPM_TOKEN }}
        registry: ${{ inputs.registry || 'https://registry.npmjs.org' }}
