name: ~npm release publish
on:
  workflow_call:

jobs:
  release:
    uses: sanzenwin/workflows/.github/workflows/release.yml@main
    permissions:
      contents: write
    secrets: inherit
  publish:
    uses: sanzenwin/workflows/.github/workflows/npm-publish.yml@main
    secrets: inherit
