name: ~python3 release publish for windows
on:
  workflow_call:
    inputs:
      os:
        type: string
        default: "windows-latest" # ubuntu-latest windows-latest macos-latest
      python_version:
        type: string
        default: "3.10"
      plat_name:
        type: string
        default: "win-amd64" # https://pypi.org/project/torch/#files
      skip_existing:
        type: string
        default: "true"
jobs:
  publish-self:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '${{ inputs.python_version }}'
      - run: python3 -m pip install -U wheel setuptools twine
      - run: python setup.py bdist_wheel ${{ inputs.plat_name && format('--plat-name={0}', inputs.plat_name) || '' }}
      - run: twine upload dist/*.whl ${{ inputs.skip_existing == 'true' && '--skip-existing' || '' }} --verbose --repository-url ${{ secrets.registry || secrets.SELFHOSTED_REGISTRY || 'https://pypi.cnb.cool/deksep/pypi-common/-/packages/simple' }}
        env:
          TWINE_USERNAME: ${{ secrets.username || secrets.SELFHOSTED_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.password || secrets.SELFHOSTED_PASSWORD }}
