name: ~python3 release publish
on:
  workflow_call:

jobs:
  release:
    uses: ./.github/workflows/release.yml
    permissions:
      contents: write
    secrets: inherit
  publish:
    needs: release
    uses: ./.github/workflows/pypi-publish.yml
    secrets: inherit
