name: ~python3 release publish
on:
  workflow_call:

jobs:
  release:
    uses: sanzenwin/workflows/.github/workflows/release.yml@main
    permissions:
      contents: write
    secrets: inherit
  publish:
    needs: release
    uses: sanzenwin/workflows/.github/workflows/pypi-publish.yml@main
    secrets: inherit
