name: ~python3 publish
on:
  workflow_call:
    secrets:
      registry:
        required: false
      username:
        required: false
      password:
        required: false
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: 3
    - uses: pdm-project/setup-pdm@v3
    - uses: actions/checkout@v3
    - run: pdm build
    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
        skip-existing: true
        repository-url: ${{ secrets.registry || secrets.SELFHOSTED_REGISTRY || 'https://deksep-pypi.pkg.coding.net/common/pypi' }}
        user: ${{ secrets.username || secrets.SELFHOSTED_USERNAME }}
        password: ${{ secrets.password || secrets.SELFHOSTED_PASSWORD }}
    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
        skip-existing: true
        repository-url: https://upload.pypi.org/legacy
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
