name: ~python3 release publish
on:
  workflow_call:

jobs:
  release:
    uses: sanzenwin/workflows/.github/workflows/release.yml
    permissions:
      contents: write
    secrets: inherit
  publish:
    uses: sanzenwin/workflows/.github/workflows/python3-publish.yml
    secrets: inherit
