name: ~python3 publish
on:
  workflow_call:
    inputs:
      registry:
        required: false
        type: string
      user:
        required: false
        type: string
    secrets:
      token:
        required: true
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: 3
    - uses: pdm-project/setup-pdm@v3
    - uses: actions/checkout@v4
    - run: pdm build
    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: ${{ inputs.registry || "https://upload.pypi.org/legacy/" }}
        user: ${{ inputs.user || "__token__" }}
        password: ${{ secrets.token || secrets.GITHUB_TOKEN }}
