name: ~python3-release publish
on:
  workflow_call:

jobs:
  release:
    uses: ./.github/workflows/release.yml
    permissions:
      contents: write
    secrets: inherit
  publish:
    uses: ./.github/workflows/python3-publish.yml
    secrets: inherit
